"""PMTiles generation from DuckLake tables.

This module provides utilities for generating PMTiles (static vector tiles)
from DuckLake tables. PMTiles enable fast tile serving without dynamic
generation overhead.

The generation pipeline:
    1. Export geometry data to GeoJSON (intermediate format)
    2. Use tippecanoe to generate PMTiles with optimal settings
    3. For polygon layers: generate a separate anchor PMTiles file with label
       anchor points using tippecanoe's --convert-polygons-to-label-points.
       The tile service concatenates MVT bytes from both files at serving time.
    4. Store PMTiles in a separate tiles directory (cache/derived data)
    5. Embed DuckLake snapshot_id in PMTiles metadata for sync tracking

Usage:
    from goatlib.io.pmtiles import PMTilesGenerator

    generator = PMTilesGenerator(tiles_data_dir="/app/data/tiles")
    pmtiles_path = generator.generate_from_table(
        duckdb_con=con,
        table_name="lake.user_xxx.t_yyy",
        user_id="xxx",
        layer_id="yyy",
        snapshot_id=1234,  # DuckLake snapshot for sync tracking
    )
"""

import json
import logging
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Self

import duckdb
from pmtiles.reader import MmapSource
from pmtiles.reader import Reader as PMTilesReader

logger = logging.getLogger(__name__)


@dataclass
class PMTilesConfig:
    """Configuration for PMTiles generation.

    Uses variable-depth tile pyramids (--generate-variable-depth-tile-pyramid)
    which only generates tiles where needed, dramatically reducing generation
    time and file size for simple features.

    Attributes:
        enabled: Whether PMTiles generation is enabled
        min_zoom: Minimum zoom level (default: 0)
        max_zoom: Maximum zoom level for tile generation (default: 14).
            Note: With variable-depth, most tiles will stop earlier if
            sufficient detail is already present.
        layer_name: Name for the MVT layer (default: "default")
        anchor_layer_name: Name for the label anchor MVT layer (default: "default_anchor").
            Only used for polygon layers — contains point features generated by
            tippecanoe's --convert-polygons-to-label-points for server-side label placement.
    """

    enabled: bool = True
    min_zoom: int = 0
    max_zoom: int = 14
    layer_name: str = "default"
    anchor_layer_name: str = "default_anchor"


class PMTilesGenerator:
    """Generate PMTiles from DuckLake tables.

    PMTiles are stored separately from source data (cache/derived data):
        /app/data/tiles/
        └── user_{user_id}/
            └── t_{layer_id}.pmtiles

    Source data remains in DuckLake:
        /app/data/ducklake/
        └── user_{user_id}/
            └── t_{layer_id}/
                └── *.parquet
    """

    def __init__(
        self: Self,
        tiles_data_dir: str = "/app/data/tiles",
        config: PMTilesConfig | None = None,
    ) -> None:
        """Initialize PMTiles generator.

        Args:
            tiles_data_dir: Root directory for tiles storage (separate from source data)
            config: PMTiles generation configuration
        """
        self.tiles_data_dir = Path(tiles_data_dir)
        self.config = config or PMTilesConfig()

        # Ensure base tiles directory exists
        try:
            self.tiles_data_dir.mkdir(parents=True, exist_ok=True)
        except FileExistsError:
            # Path exists but may be a symlink to a directory - that's OK
            if not self.tiles_data_dir.is_dir():
                raise RuntimeError(
                    f"tiles_data_dir exists but is not a directory: {self.tiles_data_dir}"
                )

        self._check_dependencies()

    def _check_dependencies(self: Self) -> bool:
        """Check if required tools are available.

        Returns:
            True if all dependencies are available

        Raises:
            RuntimeError: If tippecanoe is not installed
        """
        if not shutil.which("tippecanoe"):
            raise RuntimeError(
                "tippecanoe is required for PMTiles generation. "
                "Install it with: apt-get install tippecanoe"
            )
        return True

    def get_pmtiles_path(self: Self, user_id: str, layer_id: str) -> Path:
        """Get the path where PMTiles should be stored.

        Args:
            user_id: User UUID (without dashes)
            layer_id: Layer UUID (without dashes)

        Returns:
            Path to the PMTiles file
        """
        user_id_clean = user_id.replace("-", "")
        layer_id_clean = layer_id.replace("-", "")

        tiles_dir = self.tiles_data_dir / f"user_{user_id_clean}"
        return tiles_dir / f"t_{layer_id_clean}.pmtiles"

    def get_anchor_pmtiles_path(self: Self, user_id: str, layer_id: str) -> Path:
        """Get the path for the label anchor PMTiles file (polygon layers only).

        Anchor PMTiles contain point features generated by tippecanoe's
        --convert-polygons-to-label-points for optimal label placement.
        Stored as a separate file to avoid tile-join merge issues with
        variable-depth tile pyramids.

        Args:
            user_id: User UUID (without dashes)
            layer_id: Layer UUID (without dashes)

        Returns:
            Path to the anchor PMTiles file
        """
        main_path = self.get_pmtiles_path(user_id, layer_id)
        return main_path.with_name(main_path.stem + "_anchor.pmtiles")

    def pmtiles_exists(self: Self, user_id: str, layer_id: str) -> bool:
        """Check if PMTiles file exists for a layer.

        Args:
            user_id: User UUID
            layer_id: Layer UUID

        Returns:
            True if PMTiles file exists
        """
        return self.get_pmtiles_path(user_id, layer_id).exists()

    def is_pmtiles_valid(self: Self, pmtiles_path: Path | str) -> bool:
        """Check if a PMTiles file is valid and readable.

        Args:
            pmtiles_path: Path to PMTiles file

        Returns:
            True if the file is a valid PMTiles file
        """
        try:
            with open(pmtiles_path, "rb") as f:
                reader = PMTilesReader(MmapSource(f))
                # Try to read header - this will fail if file is corrupted
                reader.header()
            return True
        except Exception as e:
            # Log the actual error for debugging
            logger.debug(f"PMTiles validation failed for {pmtiles_path}: {e}")
            # Also check magic bytes for more info
            try:
                with open(pmtiles_path, "rb") as f:
                    magic = f.read(7)
                    logger.warning(
                        f"Invalid PMTiles {pmtiles_path}: magic={magic!r}, error={e}"
                    )
            except Exception:
                pass
            return False

    def get_pmtiles_snapshot_id(self: Self, pmtiles_path: Path | str) -> int | None:
        """Read the DuckLake snapshot_id from PMTiles metadata.

        The snapshot_id is stored in the 'description' field of PMTiles metadata
        as a JSON object: {"snapshot_id": 1234, "generated_at": "..."}

        Args:
            pmtiles_path: Path to PMTiles file

        Returns:
            Snapshot ID if found, None otherwise
        """
        try:
            with open(pmtiles_path, "rb") as f:
                reader = PMTilesReader(MmapSource(f))
                metadata = reader.metadata()
                description = metadata.get("description", "")

                # Try to parse description as JSON (our format)
                if description.startswith("{"):
                    try:
                        desc_data = json.loads(description)
                        return desc_data.get("snapshot_id")
                    except json.JSONDecodeError:
                        pass
            return None
        except Exception as e:
            logger.debug(f"Could not read snapshot_id from {pmtiles_path}: {e}")
            return None

    def is_pmtiles_in_sync(
        self: Self, pmtiles_path: Path | str, current_snapshot_id: int
    ) -> bool:
        """Check if PMTiles is in sync with the DuckLake table.

        Checks both embedded PMTiles metadata and sidecar files for
        backwards compatibility.

        Args:
            pmtiles_path: Path to PMTiles file
            current_snapshot_id: Current DuckLake snapshot ID for the table

        Returns:
            True if PMTiles was generated from the current snapshot
        """
        # First check embedded metadata
        stored_snapshot = self.get_pmtiles_snapshot_id(pmtiles_path)
        if stored_snapshot is not None:
            return stored_snapshot == current_snapshot_id

        # Fall back to sidecar file for backwards compatibility
        try:
            meta_path = Path(pmtiles_path).with_suffix(".pmtiles.meta.json")
            if meta_path.exists():
                with open(meta_path) as f:
                    meta = json.load(f)
                    stored_snapshot = meta.get("snapshot_id")
                    return stored_snapshot == current_snapshot_id
        except Exception:
            pass

        # No snapshot info found - not in sync
        return False

    def generate_from_table(
        self: Self,
        duckdb_con: duckdb.DuckDBPyConnection,
        table_name: str,
        user_id: str,
        layer_id: str,
        geometry_column: str = "geometry",
        exclude_columns: list[str] | None = None,
        snapshot_id: int | None = None,
        show_progress: bool = True,
    ) -> Path | None:
        """Generate PMTiles from a DuckLake table.

        Exports the table to GeoJSON (intermediate), then uses tippecanoe
        to generate PMTiles with optimal settings.

        Args:
            duckdb_con: DuckDB connection with DuckLake attached
            table_name: Full table path (e.g., "lake.user_xxx.t_yyy")
            user_id: User UUID
            layer_id: Layer UUID
            geometry_column: Name of the geometry column
            exclude_columns: Columns to exclude from tiles (e.g., ["bbox"])
            snapshot_id: DuckLake snapshot ID for sync tracking. If provided,
                will be embedded in PMTiles metadata.
            show_progress: If True, stream tippecanoe progress to stdout

        Returns:
            Path to generated PMTiles file, or None if generation failed
        """
        if not self.config.enabled:
            logger.debug("PMTiles generation is disabled")
            return None

        exclude_columns = exclude_columns or ["bbox"]
        pmtiles_path = self.get_pmtiles_path(user_id, layer_id)

        # Ensure tiles directory exists
        pmtiles_path.parent.mkdir(parents=True, exist_ok=True)

        logger.info(f"Generating PMTiles for {table_name} -> {pmtiles_path}")

        # Detect geometry type for optimized tippecanoe settings
        geometry_type = self._detect_geometry_type(
            duckdb_con, table_name, geometry_column
        )

        # Use a temp file for the PMTiles output, then atomically rename
        # This prevents corrupted files if the process is interrupted
        # NOTE: tippecanoe uses file extension to determine output format!
        # .pmtiles -> PMTiles, anything else -> MBTiles (SQLite)
        # So we use a .tmp_ prefix instead of .tmp suffix
        temp_pmtiles_path = pmtiles_path.parent / f".tmp_{pmtiles_path.name}"

        # Check if this is a polygon layer that needs label anchor points
        geom_upper = geometry_type.upper() if geometry_type else ""
        is_polygon = "POLYGON" in geom_upper

        # Anchor PMTiles path (separate file for polygon label points)
        anchor_pmtiles_path = self.get_anchor_pmtiles_path(user_id, layer_id)
        temp_anchor_path = (
            anchor_pmtiles_path.parent / f".tmp_{anchor_pmtiles_path.name}"
        )

        try:
            with tempfile.NamedTemporaryFile(
                suffix=".geojson", delete=True, prefix="pmtiles_"
            ) as tmp_geojson:
                # Step 1: Export to GeoJSON (preserves attribute types)
                # Note: FlatGeobuf is faster but tippecanoe converts integers to strings
                self._export_to_geojson(
                    duckdb_con=duckdb_con,
                    table_name=table_name,
                    output_path=tmp_geojson.name,
                    geometry_column=geometry_column,
                    exclude_columns=exclude_columns,
                )

                # Step 2: Generate main geometry tiles (all layer types)
                self._run_tippecanoe(
                    input_path=tmp_geojson.name,
                    output_path=str(temp_pmtiles_path),
                    geometry_type=geometry_type,
                    snapshot_id=snapshot_id,
                    show_progress=show_progress,
                )

                # Step 3: For polygon layers, generate separate anchor PMTiles
                if is_polygon:
                    logger.info("Generating label anchor point tiles...")
                    self._run_tippecanoe(
                        input_path=tmp_geojson.name,
                        output_path=str(temp_anchor_path),
                        geometry_type=geometry_type,
                        snapshot_id=snapshot_id,
                        show_progress=show_progress,
                        label_anchor=True,
                    )

            # Atomically rename temp files to final paths
            temp_pmtiles_path.rename(pmtiles_path)
            if is_polygon and temp_anchor_path.exists():
                temp_anchor_path.rename(anchor_pmtiles_path)

            size_mb = pmtiles_path.stat().st_size / 1024 / 1024
            logger.info(
                f"PMTiles generated successfully: {pmtiles_path} ({size_mb:.1f} MB)"
            )
            if is_polygon and anchor_pmtiles_path.exists():
                anchor_mb = anchor_pmtiles_path.stat().st_size / 1024 / 1024
                logger.info(
                    f"Anchor PMTiles: {anchor_pmtiles_path} ({anchor_mb:.1f} MB)"
                )

            return pmtiles_path

        except Exception as e:
            logger.error(f"PMTiles generation failed: {e}")
            # Clean up temp files if they exist
            if temp_pmtiles_path.exists():
                temp_pmtiles_path.unlink()
            if temp_anchor_path.exists():
                temp_anchor_path.unlink()
            return None

    def generate_anchor_from_table(
        self: Self,
        duckdb_con: duckdb.DuckDBPyConnection,
        table_name: str,
        user_id: str,
        layer_id: str,
        geometry_column: str = "geometry",
        exclude_columns: list[str] | None = None,
        snapshot_id: int | None = None,
        show_progress: bool = True,
    ) -> Path | None:
        """Generate only anchor PMTiles for a polygon layer.

        Exports the table to GeoJSON and generates label anchor point tiles
        without regenerating the main geometry tiles.

        Args:
            duckdb_con: DuckDB connection with DuckLake attached
            table_name: Full table path (e.g., "lake.user_xxx.t_yyy")
            user_id: User UUID
            layer_id: Layer UUID
            geometry_column: Name of the geometry column
            exclude_columns: Columns to exclude from tiles (e.g., ["bbox"])
            snapshot_id: DuckLake snapshot ID for sync tracking
            show_progress: If True, stream tippecanoe progress to stdout

        Returns:
            Path to generated anchor PMTiles file, or None if generation failed
        """
        if not self.config.enabled:
            logger.debug("PMTiles generation is disabled")
            return None

        exclude_columns = exclude_columns or ["bbox"]
        anchor_pmtiles_path = self.get_anchor_pmtiles_path(user_id, layer_id)
        anchor_pmtiles_path.parent.mkdir(parents=True, exist_ok=True)
        temp_anchor_path = (
            anchor_pmtiles_path.parent / f".tmp_{anchor_pmtiles_path.name}"
        )

        logger.info(
            f"Generating anchor PMTiles for {table_name} -> {anchor_pmtiles_path}"
        )

        # Detect geometry type to confirm it's a polygon layer
        geometry_type = self._detect_geometry_type(
            duckdb_con, table_name, geometry_column
        )
        geom_upper = geometry_type.upper() if geometry_type else ""
        if "POLYGON" not in geom_upper:
            logger.warning(
                f"Skipping anchor generation for non-polygon layer: {geometry_type}"
            )
            return None

        try:
            with tempfile.NamedTemporaryFile(
                suffix=".geojson", delete=True, prefix="pmtiles_"
            ) as tmp_geojson:
                self._export_to_geojson(
                    duckdb_con=duckdb_con,
                    table_name=table_name,
                    output_path=tmp_geojson.name,
                    geometry_column=geometry_column,
                    exclude_columns=exclude_columns,
                )

                self._run_tippecanoe(
                    input_path=tmp_geojson.name,
                    output_path=str(temp_anchor_path),
                    geometry_type=geometry_type,
                    snapshot_id=snapshot_id,
                    show_progress=show_progress,
                    label_anchor=True,
                )

            temp_anchor_path.rename(anchor_pmtiles_path)
            anchor_mb = anchor_pmtiles_path.stat().st_size / 1024 / 1024
            logger.info(
                f"Anchor PMTiles generated: {anchor_pmtiles_path} ({anchor_mb:.1f} MB)"
            )
            return anchor_pmtiles_path

        except Exception as e:
            logger.error(f"Anchor PMTiles generation failed: {e}")
            if temp_anchor_path.exists():
                temp_anchor_path.unlink()
            return None

    def _detect_geometry_type(
        self: Self,
        duckdb_con: duckdb.DuckDBPyConnection,
        table_name: str,
        geometry_column: str,
    ) -> str | None:
        """Detect the geometry type of a table.

        Args:
            duckdb_con: DuckDB connection
            table_name: Full table path
            geometry_column: Name of the geometry column

        Returns:
            Geometry type string (e.g., "POINT", "POLYGON") or None
        """
        try:
            # Query the geometry type directly from data
            # (avoids DESCRIBE which can fail with some DuckLake configurations)
            result = duckdb_con.execute(f"""
                SELECT DISTINCT ST_GeometryType("{geometry_column}")
                FROM {table_name}
                WHERE "{geometry_column}" IS NOT NULL
                LIMIT 1
            """).fetchone()
            if result:
                geom_type = result[0]
                logger.info(
                    f"Detected geometry type: {geom_type} (column: {geometry_column})"
                )
                return geom_type
        except Exception as e:
            logger.warning(f"Could not detect geometry type: {e}")
        return None

    def _export_to_geojson(
        self: Self,
        duckdb_con: duckdb.DuckDBPyConnection,
        table_name: str,
        output_path: str,
        geometry_column: str = "geometry",
        exclude_columns: list[str] | None = None,
    ) -> None:
        """Export a DuckLake table to GeoJSON format.

        GeoJSON is used as an intermediate format because:
        - tippecanoe reads it natively
        - GeoJSON preserves attribute types (integers stay integers)
        - DuckDB can write it directly via GDAL driver

        Note: We use GeoJSON instead of FlatGeobuf because tippecanoe
        converts FlatGeobuf attributes to strings, breaking numeric styles.

        Args:
            duckdb_con: DuckDB connection
            table_name: Full table path
            output_path: Output GeoJSON file path
            geometry_column: Name of geometry column
            exclude_columns: Columns to exclude (e.g., bbox struct)
        """
        exclude_columns = exclude_columns or []

        # Types that are not supported by GeoJSON/tippecanoe
        unsupported_type_prefixes = ("struct", "map", "list", "union")

        # Get actual columns and their types from the table
        columns_to_exclude: set[str] = set(exclude_columns)
        try:
            # Use SELECT LIMIT 0 to get column info without fetching data
            # This works better with DuckLake than DESCRIBE
            result = duckdb_con.execute(
                f"SELECT * FROM {table_name} LIMIT 0"
            ).description

            for col_info in result:
                col_name = col_info[0]
                col_type = col_info[1] if len(col_info) > 1 else ""

                col_type_lower = str(col_type).lower()
                # Exclude complex types that GeoJSON/tippecanoe can't handle
                if col_type_lower.startswith(unsupported_type_prefixes):
                    columns_to_exclude.add(col_name)
                    logger.debug(
                        f"Excluding column '{col_name}' with unsupported type: {col_type}"
                    )
                # Also exclude array types (e.g., VARCHAR[], INTEGER[])
                elif col_type_lower.endswith("[]"):
                    columns_to_exclude.add(col_name)
                    logger.debug(f"Excluding array column '{col_name}': {col_type}")

            actual_columns = {col_info[0] for col_info in result}
            # Only keep exclusions for columns that actually exist
            columns_to_exclude = columns_to_exclude & actual_columns

        except Exception as e:
            logger.warning(f"Could not get column list for {table_name}: {e}")
            columns_to_exclude = set()

        # Build exclusion clause for columns that exist
        exclude_clause = ""
        if columns_to_exclude:
            exclude_clause = f"EXCLUDE({', '.join(sorted(columns_to_exclude))})"
            logger.debug(f"Excluding columns from GeoJSON export: {columns_to_exclude}")

        # Include rowid+1 as _rowid — tippecanoe will promote it to MVT feature ID.
        # +1 because MVT feature ID 0 is treated as "unset" by MapLibre.
        sql = f"""
            COPY (
                SELECT rowid + 1 AS _rowid, * {exclude_clause}
                FROM {table_name}
            ) TO '{output_path}' WITH (FORMAT GDAL, DRIVER 'GeoJSON')
        """

        logger.debug(f"Exporting to GeoJSON: {sql}")
        duckdb_con.execute(sql)

    def _run_tippecanoe(
        self: Self,
        input_path: str,
        output_path: str,
        geometry_type: str | None = None,
        snapshot_id: int | None = None,
        show_progress: bool = True,
        label_anchor: bool = False,
    ) -> None:
        """Run tippecanoe to generate PMTiles.

        Uses different settings based on geometry type:
        - Points: Use drop-fraction for even distribution at low zooms
        - Polygons/Lines: Use drop-densest to preserve shapes

        Args:
            input_path: Input GeoJSON file path
            output_path: Output PMTiles file path
            geometry_type: Geometry type (e.g., "POINT", "POLYGON")
            snapshot_id: DuckLake snapshot ID to embed in PMTiles metadata
            show_progress: If True, stream tippecanoe progress to stdout
            label_anchor: If True, generate label anchor points from polygons
                using --convert-polygons-to-label-points. The output layer
                will be named using anchor_layer_name config.

        Raises:
            subprocess.CalledProcessError: If tippecanoe fails
        """
        # Use defaults if config values are None (safety check)
        min_zoom = self.config.min_zoom if self.config.min_zoom is not None else 0
        max_zoom = self.config.max_zoom if self.config.max_zoom is not None else 14

        # Detect geometry type category
        geom_upper = geometry_type.upper() if geometry_type else ""
        is_point_layer = "POINT" in geom_upper
        is_line_layer = "LINE" in geom_upper or "LINESTRING" in geom_upper

        # Use anchor layer name when generating label anchor points
        layer_name = (
            self.config.anchor_layer_name if label_anchor else self.config.layer_name
        )

        cmd = [
            "tippecanoe",
            "-o",
            output_path,
            input_path,
            "--force",
            "-l",
            layer_name,
            f"-Z{min_zoom}",
            f"-z{max_zoom}",
            "--generate-variable-depth-tile-pyramid",  # Only generate tiles where needed
            "--full-detail=16",
            "--use-attribute-for-id=_rowid",  # Promote _rowid to MVT feature ID
            "--exclude=_rowid",  # Ensure _rowid is removed from properties
        ]

        # For label anchor generation, convert polygons to optimal label points
        if label_anchor:
            cmd.append("--convert-polygons-to-label-points")

        # Embed snapshot_id in PMTiles metadata via description field
        if snapshot_id is not None:
            description_data = {
                "snapshot_id": snapshot_id,
                "generated_at": datetime.now(timezone.utc).isoformat(),
            }
            cmd.extend(["--description", json.dumps(description_data)])

        if label_anchor:
            # Label anchor settings: one point per polygon, no clustering.
            # tippecanoe's --convert-polygons-to-label-points already handles
            # optimal placement. Drop densest labels at low zooms when tiles
            # are too full (e.g. 200k+ polygons) — they appear at higher zooms.
            cmd.extend(
                [
                    "-r1",  # Minimal drop rate (keep as much as possible)
                    "--drop-densest-as-needed",
                    "--extend-zooms-if-still-dropping",
                ]
            )
            logger.info("Using label anchor tippecanoe settings (no clustering)")
        elif is_point_layer:
            # Point-specific settings:
            # - Higher limits for dense/attribute-heavy POI datasets
            # - Use -r1 to guarantee at least 1 feature per tile at all zooms
            # - Coalesce smallest for even distribution at low zooms
            cmd.extend(
                [
                    "-r1",
                    "--cluster-distance=5",
                    "--hilbert",
                    "--extend-zooms-if-still-dropping",
                ]
            )
            logger.info("Using point-optimized tippecanoe settings (-r1, high limits)")
        elif is_line_layer:
            # LineString settings (e.g., roads):
            # - Higher limits for denser output (like Felt)
            # - Allow line simplification at low zooms (default behavior)
            # - Only drop smallest lines when absolutely needed
            cmd.extend(
                [
                    "-M",
                    "2000000",  # 2MB tile size limit (default 500KB)
                    "-O",
                    "300000",  # 300K features per tile (default 200K)
                    "--drop-smallest-as-needed",  # Drop tiny road segments only if needed
                    "--extend-zooms-if-still-dropping",
                    "--simplify-only-low-zooms",
                    "--no-simplification-of-shared-nodes",
                ]
            )
            logger.info(
                "Using line-optimized tippecanoe settings (high density, simplify)"
            )
        else:
            # Polygon settings:
            # - Higher limits for dense polygon datasets (buildings, parcels)
            # - Preserve geometry detail
            # - Avoid tiny polygon reduction (keeps small buildings visible)
            # - Drop/coalesce densest areas first
            cmd.extend(
                [
                    "-M",
                    "2000000",  # 2MB tile size limit (default 500KB)
                    "-O",
                    "300000",  # 300K features per tile (default 200K)
                    "--no-tiny-polygon-reduction",
                    "--coalesce-densest-as-needed",
                    "--drop-densest-as-needed",
                    "--extend-zooms-if-still-dropping",
                    "--simplify-only-low-zooms",
                    "--no-simplification-of-shared-nodes",
                ]
            )
            logger.debug("Using polygon-optimized tippecanoe settings")

        logger.debug(f"Running tippecanoe: {' '.join(cmd)}")

        if show_progress:
            # Let tippecanoe write progress directly to terminal
            result = subprocess.run(cmd, capture_output=False)
            if result.returncode != 0:
                raise subprocess.CalledProcessError(result.returncode, cmd)
        else:
            # Capture output silently
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                error_msg = (
                    result.stderr.strip() if result.stderr else "No error message"
                )
                logger.error(
                    f"tippecanoe failed (exit {result.returncode}): {error_msg}\n"
                    f"Command: {' '.join(cmd)}"
                )
                raise subprocess.CalledProcessError(
                    result.returncode, cmd, result.stdout, result.stderr
                )
            if result.stderr:
                for line in result.stderr.strip().split("\n"):
                    if line.strip():
                        logger.debug(f"tippecanoe: {line}")

    def delete_pmtiles(self: Self, user_id: str, layer_id: str) -> bool:
        """Delete PMTiles file, anchor file, and metadata for a layer.

        Args:
            user_id: User UUID
            layer_id: Layer UUID

        Returns:
            True if file was deleted, False if it didn't exist
        """
        pmtiles_path = self.get_pmtiles_path(user_id, layer_id)
        deleted = False

        if pmtiles_path.exists():
            pmtiles_path.unlink()
            logger.info(f"Deleted PMTiles: {pmtiles_path}")
            deleted = True

        # Also delete anchor PMTiles (polygon label points)
        anchor_path = self.get_anchor_pmtiles_path(user_id, layer_id)
        if anchor_path.exists():
            anchor_path.unlink()
            logger.info(f"Deleted anchor PMTiles: {anchor_path}")

        # Also delete metadata sidecar file
        meta_path = pmtiles_path.with_suffix(".pmtiles.meta.json")
        if meta_path.exists():
            meta_path.unlink()
            logger.debug(f"Deleted PMTiles metadata: {meta_path}")

        return deleted
