import type { Browser } from "playwright-core";
import { chromium } from "playwright-core";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

describe("PDF Renderer (Integration)", () => {
  let browser: Browser;

  beforeAll(async () => {
    // Launch browser once for all tests
    browser = await chromium.launch({
      headless: true,
    });
  });

  afterAll(async () => {
    await browser?.close();
  });

  it("should launch Playwright browser", async () => {
    expect(browser).toBeDefined();
    expect(browser.isConnected()).toBe(true);
  });

  it("should create a page and navigate", async () => {
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto("about:blank");
    expect(page.url()).toBe("about:blank");

    await context.close();
  });

  it("should generate a PDF from HTML", async () => {
    const context = await browser.newContext();
    const page = await context.newPage();

    // Set simple HTML content
    await page.setContent(`
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #333; }
          </style>
        </head>
        <body>
          <h1>Test PDF</h1>
          <p>This is a test PDF generated by Playwright.</p>
        </body>
      </html>
    `);

    // Generate PDF
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    expect(pdf).toBeInstanceOf(Buffer);
    expect(pdf.length).toBeGreaterThan(0);

    // PDF signature (starts with %PDF)
    expect(pdf.toString("utf8", 0, 4)).toBe("%PDF");

    await context.close();
  }, 10000); // 10 second timeout for PDF generation

  it("should wait for content to load before PDF generation", async () => {
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.setContent(`
      <!DOCTYPE html>
      <html>
        <body>
          <div id="loading">Loading...</div>
          <div id="content" style="display: none;">Content loaded!</div>
          <script>
            setTimeout(() => {
              document.getElementById('loading').style.display = 'none';
              document.getElementById('content').style.display = 'block';
              window.contentReady = true;
            }, 100);
          </script>
        </body>
      </html>
    `);

    // Wait for content to be ready
    await page.waitForFunction("window.contentReady === true", { timeout: 5000 });

    const content = await page.textContent("#content");
    expect(content).toBe("Content loaded!");

    await context.close();
  });

  it("should handle page dimensions correctly", async () => {
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.setContent("<h1>Test</h1>");

    // Generate PDF with custom dimensions
    const pdf = await page.pdf({
      width: "210mm", // A4 width
      height: "297mm", // A4 height
      printBackground: true,
      margin: {
        top: "10mm",
        right: "10mm",
        bottom: "10mm",
        left: "10mm",
      },
    });

    expect(pdf).toBeInstanceOf(Buffer);
    expect(pdf.length).toBeGreaterThan(0);

    await context.close();
  });

  it("should capture high-DPI screenshots", async () => {
    const context = await browser.newContext({
      viewport: { width: 1920, height: 1080 },
      deviceScaleFactor: 2, // Retina quality
    });
    const page = await context.newPage();

    await page.setContent(`
      <div style="width: 200px; height: 200px; background: red;"></div>
    `);

    const screenshot = await page.screenshot({
      type: "png",
    });

    expect(screenshot).toBeInstanceOf(Buffer);
    expect(screenshot.length).toBeGreaterThan(0);

    // PNG signature
    expect(screenshot.toString("hex", 0, 8)).toBe("89504e470d0a1a0a");

    await context.close();
  });
});
