"""Integration tests for computed-column recompute in FeatureWriteService.

These tests exercise the four write methods (create_feature, create_features_bulk,
update_feature_properties, replace_feature) with a real in-memory DuckDB
database so that the SQL fragments generated by ComputedColumnSpec are
actually executed and the results are observable.

The DuckLake write manager is replaced by a lightweight fake that uses a
plain DuckDB connection; the LayerInfo and column list are constructed
directly.  This avoids the full DuckLake / DuckLake-catalog / asyncpg
stack while still executing the SQL.

NOTE: These are *functional* tests for the service layer, not end-to-end
HTTP tests.  End-to-end HTTP tests (including the asyncpg fetch_field_config
path in the router) require running infrastructure and are tracked as a gap
for task G1 / D2.
"""

from __future__ import annotations

import json
from contextlib import contextmanager
from typing import Any, Generator
from unittest.mock import patch

import duckdb

from geoapi.dependencies import LayerInfo
from geoapi.routers.metadata import (
    _apply_field_config_to_properties,
    _kind_from_json_type,
)
from geoapi.services.feature_write_service import FeatureWriteService

# ---------------------------------------------------------------------------
# Helpers / fixtures
# ---------------------------------------------------------------------------

# A square polygon in EPSG:4326 roughly centred on Munich (~1 km side).
# We use a tiny square so ST_Area_Spheroid returns a non-zero value we can
# detect, but we only assert > 0 rather than a precise value.
POLYGON_GEOJSON: dict[str, Any] = {
    "type": "Polygon",
    "coordinates": [
        [
            [11.5, 48.1],
            [11.51, 48.1],
            [11.51, 48.11],
            [11.5, 48.11],
            [11.5, 48.1],
        ]
    ],
}

# field_config for a layer with one computed area column.
FIELD_CONFIG_WITH_AREA: dict[str, Any] = {
    "area_m2": {
        "is_computed": True,
        "kind": "area",
        "depends_on": ["geometry"],
    }
}


class _FakeCon:
    """Thin wrapper that adapts a DuckDB connection to the 'context manager'
    interface expected by ducklake_write_manager.connection()."""

    def __init__(self, con: duckdb.DuckDBPyConnection) -> None:
        self._con = con

    def execute(self, query: str, params: list[Any] | None = None) -> Any:
        if params:
            return self._con.execute(query, params)
        return self._con.execute(query)

    def fetchone(self) -> Any:
        return self._con.fetchone()


class _FakeManager:
    """Replaces ducklake_write_manager for tests."""

    def __init__(self, con: duckdb.DuckDBPyConnection) -> None:
        self._raw = con

    @contextmanager
    def connection(self) -> Generator[_FakeCon, None, None]:
        yield _FakeCon(self._raw)


def _make_layer_info(schema: str = "test_schema", table: str = "features") -> LayerInfo:
    return LayerInfo(
        layer_id="abc123de-f456-7890-1234-5678901234ab",
        schema_name=schema,
        table_name=table,
    )


def _setup_db() -> tuple[duckdb.DuckDBPyConnection, LayerInfo]:
    """Create an in-memory DuckDB database with spatial extension and a
    test table that includes an area_m2 column.

    The DuckLake write service uses `lake.<schema>.<table>` as the fully
    qualified table name (via LayerInfo.full_table_name).  We replicate
    that structure by attaching a second in-memory database as 'lake' and
    creating the required schema + table inside it.
    """
    con = duckdb.connect(":memory:")
    con.execute("INSTALL spatial; LOAD spatial;")
    # Attach a second in-memory DB as the 'lake' catalog so that
    # three-part names (lake.<schema>.<table>) resolve correctly.
    con.execute("ATTACH ':memory:' AS lake;")
    con.execute("CREATE SCHEMA lake.test_schema;")
    con.execute(
        """
        CREATE TABLE lake.test_schema.features (
            geometry  GEOMETRY,
            name      VARCHAR,
            area_m2   DOUBLE,
            bbox      STRUCT(xmin DOUBLE, ymin DOUBLE, xmax DOUBLE, ymax DOUBLE)
        )
        """
    )
    layer_info = _make_layer_info()
    return con, layer_info


COLUMN_NAMES = ["geometry", "name", "area_m2", "bbox"]


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestComputedColumnsInWriteService:
    """Tests that verify computed-column recompute via FeatureWriteService."""

    def _make_service_and_patch(
        self, con: duckdb.DuckDBPyConnection
    ) -> FeatureWriteService:
        """Return a FeatureWriteService whose write manager is the fake."""
        svc = FeatureWriteService()
        return svc

    # ------------------------------------------------------------------
    def test_create_feature_populates_area(self) -> None:
        """Creating a polygon feature with field_config populates area_m2."""
        con, layer_info = _setup_db()
        fake_mgr = _FakeManager(con)
        svc = FeatureWriteService()

        with patch(
            "geoapi.services.feature_write_service.ducklake_write_manager", fake_mgr
        ):
            fid = svc.create_feature(
                layer_info=layer_info,
                geometry=POLYGON_GEOJSON,
                properties={"name": "Munich"},
                column_names=COLUMN_NAMES,
                geometry_column="geometry",
                field_config=FIELD_CONFIG_WITH_AREA,
            )

        assert fid is not None
        row = con.execute("SELECT area_m2 FROM lake.test_schema.features").fetchone()
        assert row is not None
        assert row[0] is not None, "area_m2 should have been populated"
        assert row[0] > 0, "area_m2 should be positive"

    # ------------------------------------------------------------------
    def test_user_supplied_value_for_computed_column_is_stripped(self) -> None:
        """User-supplied area_m2=999 must be silently ignored; computed value wins."""
        con, layer_info = _setup_db()
        fake_mgr = _FakeManager(con)
        svc = FeatureWriteService()

        with patch(
            "geoapi.services.feature_write_service.ducklake_write_manager", fake_mgr
        ):
            svc.create_feature(
                layer_info=layer_info,
                geometry=POLYGON_GEOJSON,
                properties={"name": "Berlin", "area_m2": 999.0},
                column_names=COLUMN_NAMES,
                geometry_column="geometry",
                field_config=FIELD_CONFIG_WITH_AREA,
            )

        row = con.execute("SELECT area_m2 FROM lake.test_schema.features").fetchone()
        assert row is not None
        assert row[0] != 999.0, "User-supplied value must be stripped"
        assert row[0] > 0, "Computed area must be positive"

    # ------------------------------------------------------------------
    def test_property_only_update_does_not_recompute(self) -> None:
        """Updating a non-geometry property must NOT recompute area_m2."""
        con, layer_info = _setup_db()
        fake_mgr = _FakeManager(con)
        svc = FeatureWriteService()

        # Insert a row with a known area first (bypassing the service).
        geom_json = json.dumps(POLYGON_GEOJSON)
        con.execute(
            "INSERT INTO lake.test_schema.features (geometry, name, area_m2) "
            "VALUES (ST_GeomFromGeoJSON(?), 'Initial', 42.0)",
            [geom_json],
        )
        rowid_row = con.execute(
            "SELECT rowid FROM lake.test_schema.features"
        ).fetchone()
        assert rowid_row is not None
        # feature_id = rowid + 1
        feature_id = str(rowid_row[0] + 1)

        with patch(
            "geoapi.services.feature_write_service.ducklake_write_manager", fake_mgr
        ):
            found = svc.update_feature_properties(
                layer_info=layer_info,
                feature_id=feature_id,
                properties={"name": "Updated"},
                column_names=COLUMN_NAMES,
                field_config=FIELD_CONFIG_WITH_AREA,
            )

        assert found is True
        row = con.execute(
            "SELECT name, area_m2 FROM lake.test_schema.features"
        ).fetchone()
        assert row is not None
        assert row[0] == "Updated"
        # area is NOT in the changed set (we only changed "name"), so no recompute
        assert row[1] == 42.0, "area_m2 must not be recomputed when only name changes"

    # ------------------------------------------------------------------
    def test_geometry_replace_recomputes_area(self) -> None:
        """Replacing geometry via replace_feature must recompute area_m2."""
        con, layer_info = _setup_db()
        fake_mgr = _FakeManager(con)
        svc = FeatureWriteService()

        # Insert a row with area_m2 = 42 (sentinel) so we can confirm it changes.
        geom_json = json.dumps(POLYGON_GEOJSON)
        con.execute(
            "INSERT INTO lake.test_schema.features (geometry, name, area_m2) "
            "VALUES (ST_GeomFromGeoJSON(?), 'before', 42.0)",
            [geom_json],
        )
        rowid_row = con.execute(
            "SELECT rowid FROM lake.test_schema.features"
        ).fetchone()
        assert rowid_row is not None
        feature_id = str(rowid_row[0] + 1)

        # A slightly larger polygon to get a different area.
        bigger_polygon: dict[str, Any] = {
            "type": "Polygon",
            "coordinates": [
                [
                    [11.5, 48.1],
                    [11.52, 48.1],
                    [11.52, 48.12],
                    [11.5, 48.12],
                    [11.5, 48.1],
                ]
            ],
        }

        with patch(
            "geoapi.services.feature_write_service.ducklake_write_manager", fake_mgr
        ):
            found = svc.replace_feature(
                layer_info=layer_info,
                feature_id=feature_id,
                geometry=bigger_polygon,
                properties={"name": "after"},
                column_names=COLUMN_NAMES,
                geometry_column="geometry",
                field_config=FIELD_CONFIG_WITH_AREA,
            )

        assert found is True
        row = con.execute("SELECT area_m2 FROM lake.test_schema.features").fetchone()
        assert row is not None
        assert row[0] != 42.0, "area_m2 must be recomputed after geometry replace"
        assert row[0] > 0, "Recomputed area must be positive"

    # ------------------------------------------------------------------
    def test_create_features_bulk_populates_area(self) -> None:
        """Bulk-create populates area_m2 for every feature."""
        con, layer_info = _setup_db()
        fake_mgr = _FakeManager(con)
        svc = FeatureWriteService()

        features = [
            {"geometry": POLYGON_GEOJSON, "properties": {"name": "A"}},
            {"geometry": POLYGON_GEOJSON, "properties": {"name": "B"}},
        ]

        with patch(
            "geoapi.services.feature_write_service.ducklake_write_manager", fake_mgr
        ):
            ids = svc.create_features_bulk(
                layer_info=layer_info,
                features=features,
                column_names=COLUMN_NAMES,
                geometry_column="geometry",
                field_config=FIELD_CONFIG_WITH_AREA,
            )

        assert len(ids) == 2
        rows = con.execute(
            "SELECT area_m2 FROM lake.test_schema.features ORDER BY rowid"
        ).fetchall()
        assert len(rows) == 2
        for (area,) in rows:
            assert (
                area is not None and area > 0
            ), "Every bulk-created row must have area"


# ---------------------------------------------------------------------------
# Unit tests for queryables augmentation (_apply_field_config_to_properties)
# ---------------------------------------------------------------------------


class TestApplyFieldConfigToProperties:
    """Unit tests for the pure helper that enriches queryables properties."""

    def test_kind_from_json_type_numeric(self) -> None:
        """number and integer JSON types map to kind 'number'."""
        assert _kind_from_json_type("number") == "number"
        assert _kind_from_json_type("integer") == "number"

    def test_kind_from_json_type_string_fallback(self) -> None:
        """Any non-numeric JSON type maps to kind 'string'."""
        for t in ("string", "boolean", "object", "geometry"):
            assert _kind_from_json_type(t) == "string", f"Failed for type={t!r}"

    def test_augments_with_explicit_field_config(self) -> None:
        """Properties whose names appear in field_config get their metadata."""
        properties: dict = {
            "area_m2": {"name": "area_m2", "type": "number"},
            "label": {"name": "label", "type": "string"},
        }
        field_config = {
            "area_m2": {
                "kind": "area",
                "is_computed": True,
                "display_config": {"unit": "m²"},
            }
        }
        _apply_field_config_to_properties(properties, field_config)

        assert properties["area_m2"]["kind"] == "area"
        assert properties["area_m2"]["is_computed"] is True
        assert properties["area_m2"]["display_config"] == {"unit": "m²"}

    def test_fallback_for_columns_without_field_config(self) -> None:
        """Columns absent from field_config get sensible defaults."""
        properties: dict = {
            "score": {"name": "score", "type": "number"},
            "name": {"name": "name", "type": "string"},
        }
        _apply_field_config_to_properties(properties, {})

        assert properties["score"]["kind"] == "number"
        assert properties["score"]["is_computed"] is False
        assert properties["score"]["display_config"] == {}

        assert properties["name"]["kind"] == "string"
        assert properties["name"]["is_computed"] is False
        assert properties["name"]["display_config"] == {}

    def test_geometry_ref_entry_is_skipped(self) -> None:
        """Geometry $ref entries must not be augmented with kind/is_computed."""
        properties: dict = {
            "geom": {"$ref": "https://geojson.org/schema/Geometry.json"},
            "name": {"name": "name", "type": "string"},
        }
        _apply_field_config_to_properties(properties, {})

        # geom entry untouched — no extra keys injected
        assert "kind" not in properties["geom"]
        assert "is_computed" not in properties["geom"]
        assert "display_config" not in properties["geom"]

        # name entry still augmented
        assert properties["name"]["kind"] == "string"

    def test_existing_json_type_preserved(self) -> None:
        """Adding kind/is_computed/display_config must not drop the 'type' key."""
        properties: dict = {
            "count": {"name": "count", "type": "integer"},
        }
        _apply_field_config_to_properties(properties, {})

        assert properties["count"]["type"] == "integer"
        assert properties["count"]["kind"] == "number"  # inferred from integer

    def test_field_config_kind_takes_priority_over_inferred(self) -> None:
        """An explicit kind in field_config overrides the inferred kind."""
        properties: dict = {
            "pop_density": {"name": "pop_density", "type": "number"},
        }
        field_config = {
            "pop_density": {
                "kind": "density",
                "is_computed": False,
                "display_config": {},
            }
        }
        _apply_field_config_to_properties(properties, field_config)

        assert properties["pop_density"]["kind"] == "density"
