"""Function registry for the Formula Builder.

This module defines all allowed functions that can be used in expressions.
Each function has metadata including syntax, examples, and localized descriptions.
"""

from dataclasses import dataclass, field
from enum import Enum


class FunctionCategory(str, Enum):
    """Categories for organizing functions in the UI."""

    MATH = "math"
    STRING = "string"
    DATE = "date"
    AGGREGATE = "aggregate"
    WINDOW = "window"
    SPATIAL = "spatial"
    CONDITIONAL = "conditional"


@dataclass
class FunctionParameter:
    """A parameter for a function."""

    name: str
    type: str  # e.g., "NUMERIC", "VARCHAR", "ANY"
    description_key: str  # i18n key like "param_x"
    optional: bool = False
    default: str | None = None


@dataclass
class FunctionDoc:
    """Documentation for a single function."""

    name: str
    syntax: str
    example: str
    category: FunctionCategory
    description_key: str  # i18n key like "abs" -> t("fn.abs.description")
    return_type: str
    parameters: list[FunctionParameter] = field(default_factory=list)
    min_args: int = 0
    max_args: int | None = None  # None = unlimited
    requires_over: bool = False  # True for window functions


# =============================================================================
# FUNCTION REGISTRY
# =============================================================================

FUNCTION_REGISTRY: dict[str, FunctionDoc] = {
    # -------------------------------------------------------------------------
    # MATH FUNCTIONS
    # -------------------------------------------------------------------------
    "abs": FunctionDoc(
        name="abs",
        syntax="abs(x)",
        example='abs("temperature")',
        category=FunctionCategory.MATH,
        description_key="abs",
        return_type="NUMERIC",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "round": FunctionDoc(
        name="round",
        syntax="round(x, decimals)",
        example='round("price", 2)',
        category=FunctionCategory.MATH,
        description_key="round",
        return_type="NUMERIC",
        parameters=[
            FunctionParameter("x", "NUMERIC", "param_x"),
            FunctionParameter(
                "decimals", "INTEGER", "param_decimals", optional=True, default="0"
            ),
        ],
        min_args=1,
        max_args=2,
    ),
    "floor": FunctionDoc(
        name="floor",
        syntax="floor(x)",
        example='floor("value")',
        category=FunctionCategory.MATH,
        description_key="floor",
        return_type="BIGINT",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "ceil": FunctionDoc(
        name="ceil",
        syntax="ceil(x)",
        example='ceil("value")',
        category=FunctionCategory.MATH,
        description_key="ceil",
        return_type="BIGINT",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "trunc": FunctionDoc(
        name="trunc",
        syntax="trunc(x, decimals)",
        example='trunc("value", 2)',
        category=FunctionCategory.MATH,
        description_key="trunc",
        return_type="NUMERIC",
        parameters=[
            FunctionParameter("x", "NUMERIC", "param_x"),
            FunctionParameter(
                "decimals", "INTEGER", "param_decimals", optional=True, default="0"
            ),
        ],
        min_args=1,
        max_args=2,
    ),
    "sqrt": FunctionDoc(
        name="sqrt",
        syntax="sqrt(x)",
        example='sqrt("area")',
        category=FunctionCategory.MATH,
        description_key="sqrt",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "power": FunctionDoc(
        name="power",
        syntax="power(base, exponent)",
        example='power("radius", 2)',
        category=FunctionCategory.MATH,
        description_key="power",
        return_type="DOUBLE",
        parameters=[
            FunctionParameter("base", "NUMERIC", "param_base"),
            FunctionParameter("exponent", "NUMERIC", "param_exponent"),
        ],
        min_args=2,
        max_args=2,
    ),
    "exp": FunctionDoc(
        name="exp",
        syntax="exp(x)",
        example='exp("growth_rate")',
        category=FunctionCategory.MATH,
        description_key="exp",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "ln": FunctionDoc(
        name="ln",
        syntax="ln(x)",
        example='ln("value")',
        category=FunctionCategory.MATH,
        description_key="ln",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "log": FunctionDoc(
        name="log",
        syntax="log(x)",
        example='log("value")',
        category=FunctionCategory.MATH,
        description_key="log",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "log10": FunctionDoc(
        name="log10",
        syntax="log10(x)",
        example='log10("value")',
        category=FunctionCategory.MATH,
        description_key="log10",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "log2": FunctionDoc(
        name="log2",
        syntax="log2(x)",
        example='log2("value")',
        category=FunctionCategory.MATH,
        description_key="log2",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "sign": FunctionDoc(
        name="sign",
        syntax="sign(x)",
        example='sign("change")',
        category=FunctionCategory.MATH,
        description_key="sign",
        return_type="INTEGER",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "greatest": FunctionDoc(
        name="greatest",
        syntax="greatest(a, b, ...)",
        example='greatest("col_a", "col_b", 0)',
        category=FunctionCategory.MATH,
        description_key="greatest",
        return_type="ANY",
        parameters=[FunctionParameter("values", "ANY", "param_values")],
        min_args=2,
        max_args=None,
    ),
    "least": FunctionDoc(
        name="least",
        syntax="least(a, b, ...)",
        example='least("col_a", "col_b", 100)',
        category=FunctionCategory.MATH,
        description_key="least",
        return_type="ANY",
        parameters=[FunctionParameter("values", "ANY", "param_values")],
        min_args=2,
        max_args=None,
    ),
    "pi": FunctionDoc(
        name="pi",
        syntax="pi()",
        example='pi() * power("radius", 2)',
        category=FunctionCategory.MATH,
        description_key="pi",
        return_type="DOUBLE",
        parameters=[],
        min_args=0,
        max_args=0,
    ),
    "sin": FunctionDoc(
        name="sin",
        syntax="sin(x)",
        example='sin(radians("angle"))',
        category=FunctionCategory.MATH,
        description_key="sin",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_radians")],
        min_args=1,
        max_args=1,
    ),
    "cos": FunctionDoc(
        name="cos",
        syntax="cos(x)",
        example='cos(radians("angle"))',
        category=FunctionCategory.MATH,
        description_key="cos",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_radians")],
        min_args=1,
        max_args=1,
    ),
    "tan": FunctionDoc(
        name="tan",
        syntax="tan(x)",
        example='tan(radians("angle"))',
        category=FunctionCategory.MATH,
        description_key="tan",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_radians")],
        min_args=1,
        max_args=1,
    ),
    "radians": FunctionDoc(
        name="radians",
        syntax="radians(degrees)",
        example="radians(90)",
        category=FunctionCategory.MATH,
        description_key="radians",
        return_type="DOUBLE",
        parameters=[FunctionParameter("degrees", "NUMERIC", "param_degrees")],
        min_args=1,
        max_args=1,
    ),
    "degrees": FunctionDoc(
        name="degrees",
        syntax="degrees(radians)",
        example='degrees("angle_rad")',
        category=FunctionCategory.MATH,
        description_key="degrees",
        return_type="DOUBLE",
        parameters=[FunctionParameter("radians", "NUMERIC", "param_radians")],
        min_args=1,
        max_args=1,
    ),
    "mod": FunctionDoc(
        name="mod",
        syntax="mod(x, y)",
        example='mod("value", 10)',
        category=FunctionCategory.MATH,
        description_key="mod",
        return_type="NUMERIC",
        parameters=[
            FunctionParameter("x", "NUMERIC", "param_x"),
            FunctionParameter("y", "NUMERIC", "param_y"),
        ],
        min_args=2,
        max_args=2,
    ),
    # -------------------------------------------------------------------------
    # STRING FUNCTIONS
    # -------------------------------------------------------------------------
    "length": FunctionDoc(
        name="length",
        syntax="length(s)",
        example='length("name")',
        category=FunctionCategory.STRING,
        description_key="length",
        return_type="INTEGER",
        parameters=[FunctionParameter("s", "VARCHAR", "param_s")],
        min_args=1,
        max_args=1,
    ),
    "lower": FunctionDoc(
        name="lower",
        syntax="lower(s)",
        example='lower("name")',
        category=FunctionCategory.STRING,
        description_key="lower",
        return_type="VARCHAR",
        parameters=[FunctionParameter("s", "VARCHAR", "param_s")],
        min_args=1,
        max_args=1,
    ),
    "upper": FunctionDoc(
        name="upper",
        syntax="upper(s)",
        example='upper("code")',
        category=FunctionCategory.STRING,
        description_key="upper",
        return_type="VARCHAR",
        parameters=[FunctionParameter("s", "VARCHAR", "param_s")],
        min_args=1,
        max_args=1,
    ),
    "trim": FunctionDoc(
        name="trim",
        syntax="trim(s)",
        example='trim("input")',
        category=FunctionCategory.STRING,
        description_key="trim",
        return_type="VARCHAR",
        parameters=[FunctionParameter("s", "VARCHAR", "param_s")],
        min_args=1,
        max_args=1,
    ),
    "ltrim": FunctionDoc(
        name="ltrim",
        syntax="ltrim(s)",
        example='ltrim("padded")',
        category=FunctionCategory.STRING,
        description_key="ltrim",
        return_type="VARCHAR",
        parameters=[FunctionParameter("s", "VARCHAR", "param_s")],
        min_args=1,
        max_args=1,
    ),
    "rtrim": FunctionDoc(
        name="rtrim",
        syntax="rtrim(s)",
        example='rtrim("padded")',
        category=FunctionCategory.STRING,
        description_key="rtrim",
        return_type="VARCHAR",
        parameters=[FunctionParameter("s", "VARCHAR", "param_s")],
        min_args=1,
        max_args=1,
    ),
    "concat": FunctionDoc(
        name="concat",
        syntax="concat(a, b, ...)",
        example='concat("first", \' \', "last")',
        category=FunctionCategory.STRING,
        description_key="concat",
        return_type="VARCHAR",
        parameters=[FunctionParameter("values", "ANY", "param_values")],
        min_args=1,
        max_args=None,
    ),
    "concat_ws": FunctionDoc(
        name="concat_ws",
        syntax="concat_ws(separator, a, b, ...)",
        example='concat_ws(\', \', "city", "country")',
        category=FunctionCategory.STRING,
        description_key="concat_ws",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("separator", "VARCHAR", "param_separator"),
            FunctionParameter("values", "ANY", "param_values"),
        ],
        min_args=2,
        max_args=None,
    ),
    "substring": FunctionDoc(
        name="substring",
        syntax="substring(s, start, length)",
        example='substring("code", 1, 3)',
        category=FunctionCategory.STRING,
        description_key="substring",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("start", "INTEGER", "param_start"),
            FunctionParameter("length", "INTEGER", "param_length", optional=True),
        ],
        min_args=2,
        max_args=3,
    ),
    "left": FunctionDoc(
        name="left",
        syntax="left(s, n)",
        example='left("postal_code", 2)',
        category=FunctionCategory.STRING,
        description_key="left",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("n", "INTEGER", "param_n"),
        ],
        min_args=2,
        max_args=2,
    ),
    "right": FunctionDoc(
        name="right",
        syntax="right(s, n)",
        example='right("phone", 4)',
        category=FunctionCategory.STRING,
        description_key="right",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("n", "INTEGER", "param_n"),
        ],
        min_args=2,
        max_args=2,
    ),
    "replace": FunctionDoc(
        name="replace",
        syntax="replace(s, from, to)",
        example="replace(\"text\", 'old', 'new')",
        category=FunctionCategory.STRING,
        description_key="replace",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("from", "VARCHAR", "param_from"),
            FunctionParameter("to", "VARCHAR", "param_to"),
        ],
        min_args=3,
        max_args=3,
    ),
    "split_part": FunctionDoc(
        name="split_part",
        syntax="split_part(s, delimiter, index)",
        example="split_part(\"a-b-c\", '-', 2)",
        category=FunctionCategory.STRING,
        description_key="split_part",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("delimiter", "VARCHAR", "param_delimiter"),
            FunctionParameter("index", "INTEGER", "param_index"),
        ],
        min_args=3,
        max_args=3,
    ),
    "strpos": FunctionDoc(
        name="strpos",
        syntax="strpos(s, substring)",
        example="strpos(\"hello\", 'l')",
        category=FunctionCategory.STRING,
        description_key="strpos",
        return_type="INTEGER",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("substring", "VARCHAR", "param_substring"),
        ],
        min_args=2,
        max_args=2,
    ),
    "contains": FunctionDoc(
        name="contains",
        syntax="contains(s, substring)",
        example="contains(\"name\", 'park')",
        category=FunctionCategory.STRING,
        description_key="contains",
        return_type="BOOLEAN",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("substring", "VARCHAR", "param_substring"),
        ],
        min_args=2,
        max_args=2,
    ),
    "starts_with": FunctionDoc(
        name="starts_with",
        syntax="starts_with(s, prefix)",
        example="starts_with(\"code\", 'DE')",
        category=FunctionCategory.STRING,
        description_key="starts_with",
        return_type="BOOLEAN",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("prefix", "VARCHAR", "param_prefix"),
        ],
        min_args=2,
        max_args=2,
    ),
    "ends_with": FunctionDoc(
        name="ends_with",
        syntax="ends_with(s, suffix)",
        example="ends_with(\"file\", '.csv')",
        category=FunctionCategory.STRING,
        description_key="ends_with",
        return_type="BOOLEAN",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("suffix", "VARCHAR", "param_suffix"),
        ],
        min_args=2,
        max_args=2,
    ),
    "lpad": FunctionDoc(
        name="lpad",
        syntax="lpad(s, length, pad)",
        example="lpad(\"id\", 5, '0')",
        category=FunctionCategory.STRING,
        description_key="lpad",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("length", "INTEGER", "param_length"),
            FunctionParameter("pad", "VARCHAR", "param_pad"),
        ],
        min_args=2,
        max_args=3,
    ),
    "rpad": FunctionDoc(
        name="rpad",
        syntax="rpad(s, length, pad)",
        example="rpad(\"code\", 10, ' ')",
        category=FunctionCategory.STRING,
        description_key="rpad",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("length", "INTEGER", "param_length"),
            FunctionParameter("pad", "VARCHAR", "param_pad"),
        ],
        min_args=2,
        max_args=3,
    ),
    "reverse": FunctionDoc(
        name="reverse",
        syntax="reverse(s)",
        example='reverse("text")',
        category=FunctionCategory.STRING,
        description_key="reverse",
        return_type="VARCHAR",
        parameters=[FunctionParameter("s", "VARCHAR", "param_s")],
        min_args=1,
        max_args=1,
    ),
    "regexp_replace": FunctionDoc(
        name="regexp_replace",
        syntax="regexp_replace(s, pattern, replacement)",
        example="regexp_replace(\"text\", '\\\\d+', '#')",
        category=FunctionCategory.STRING,
        description_key="regexp_replace",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("s", "VARCHAR", "param_s"),
            FunctionParameter("pattern", "VARCHAR", "param_pattern"),
            FunctionParameter("replacement", "VARCHAR", "param_replacement"),
        ],
        min_args=3,
        max_args=3,
    ),
    # -------------------------------------------------------------------------
    # DATE/TIME FUNCTIONS
    # -------------------------------------------------------------------------
    "current_date": FunctionDoc(
        name="current_date",
        syntax="current_date",
        example="current_date",
        category=FunctionCategory.DATE,
        description_key="current_date",
        return_type="DATE",
        parameters=[],
        min_args=0,
        max_args=0,
    ),
    "current_timestamp": FunctionDoc(
        name="current_timestamp",
        syntax="current_timestamp",
        example="current_timestamp",
        category=FunctionCategory.DATE,
        description_key="current_timestamp",
        return_type="TIMESTAMP",
        parameters=[],
        min_args=0,
        max_args=0,
    ),
    "now": FunctionDoc(
        name="now",
        syntax="now()",
        example="now()",
        category=FunctionCategory.DATE,
        description_key="now",
        return_type="TIMESTAMP",
        parameters=[],
        min_args=0,
        max_args=0,
    ),
    "year": FunctionDoc(
        name="year",
        syntax="year(date)",
        example='year("created_at")',
        category=FunctionCategory.DATE,
        description_key="year",
        return_type="INTEGER",
        parameters=[FunctionParameter("date", "DATE", "param_date")],
        min_args=1,
        max_args=1,
    ),
    "month": FunctionDoc(
        name="month",
        syntax="month(date)",
        example='month("date")',
        category=FunctionCategory.DATE,
        description_key="month",
        return_type="INTEGER",
        parameters=[FunctionParameter("date", "DATE", "param_date")],
        min_args=1,
        max_args=1,
    ),
    "day": FunctionDoc(
        name="day",
        syntax="day(date)",
        example='day("date")',
        category=FunctionCategory.DATE,
        description_key="day",
        return_type="INTEGER",
        parameters=[FunctionParameter("date", "DATE", "param_date")],
        min_args=1,
        max_args=1,
    ),
    "hour": FunctionDoc(
        name="hour",
        syntax="hour(timestamp)",
        example='hour("timestamp")',
        category=FunctionCategory.DATE,
        description_key="hour",
        return_type="INTEGER",
        parameters=[FunctionParameter("timestamp", "TIMESTAMP", "param_timestamp")],
        min_args=1,
        max_args=1,
    ),
    "minute": FunctionDoc(
        name="minute",
        syntax="minute(timestamp)",
        example='minute("timestamp")',
        category=FunctionCategory.DATE,
        description_key="minute",
        return_type="INTEGER",
        parameters=[FunctionParameter("timestamp", "TIMESTAMP", "param_timestamp")],
        min_args=1,
        max_args=1,
    ),
    "second": FunctionDoc(
        name="second",
        syntax="second(timestamp)",
        example='second("timestamp")',
        category=FunctionCategory.DATE,
        description_key="second",
        return_type="INTEGER",
        parameters=[FunctionParameter("timestamp", "TIMESTAMP", "param_timestamp")],
        min_args=1,
        max_args=1,
    ),
    "dayofweek": FunctionDoc(
        name="dayofweek",
        syntax="dayofweek(date)",
        example='dayofweek("date")',
        category=FunctionCategory.DATE,
        description_key="dayofweek",
        return_type="INTEGER",
        parameters=[FunctionParameter("date", "DATE", "param_date")],
        min_args=1,
        max_args=1,
    ),
    "dayofyear": FunctionDoc(
        name="dayofyear",
        syntax="dayofyear(date)",
        example='dayofyear("date")',
        category=FunctionCategory.DATE,
        description_key="dayofyear",
        return_type="INTEGER",
        parameters=[FunctionParameter("date", "DATE", "param_date")],
        min_args=1,
        max_args=1,
    ),
    "week": FunctionDoc(
        name="week",
        syntax="week(date)",
        example='week("date")',
        category=FunctionCategory.DATE,
        description_key="week",
        return_type="INTEGER",
        parameters=[FunctionParameter("date", "DATE", "param_date")],
        min_args=1,
        max_args=1,
    ),
    "quarter": FunctionDoc(
        name="quarter",
        syntax="quarter(date)",
        example='quarter("date")',
        category=FunctionCategory.DATE,
        description_key="quarter",
        return_type="INTEGER",
        parameters=[FunctionParameter("date", "DATE", "param_date")],
        min_args=1,
        max_args=1,
    ),
    "date_part": FunctionDoc(
        name="date_part",
        syntax="date_part(part, date)",
        example="date_part('year', \"date\")",
        category=FunctionCategory.DATE,
        description_key="date_part",
        return_type="INTEGER",
        parameters=[
            FunctionParameter("part", "VARCHAR", "param_part"),
            FunctionParameter("date", "DATE", "param_date"),
        ],
        min_args=2,
        max_args=2,
    ),
    "date_trunc": FunctionDoc(
        name="date_trunc",
        syntax="date_trunc(part, date)",
        example="date_trunc('month', \"date\")",
        category=FunctionCategory.DATE,
        description_key="date_trunc",
        return_type="TIMESTAMP",
        parameters=[
            FunctionParameter("part", "VARCHAR", "param_part"),
            FunctionParameter("date", "DATE", "param_date"),
        ],
        min_args=2,
        max_args=2,
    ),
    "date_diff": FunctionDoc(
        name="date_diff",
        syntax="date_diff(part, start, end)",
        example='date_diff(\'day\', "start_date", "end_date")',
        category=FunctionCategory.DATE,
        description_key="date_diff",
        return_type="BIGINT",
        parameters=[
            FunctionParameter("part", "VARCHAR", "param_part"),
            FunctionParameter("start", "DATE", "param_start"),
            FunctionParameter("end", "DATE", "param_end"),
        ],
        min_args=3,
        max_args=3,
    ),
    "make_date": FunctionDoc(
        name="make_date",
        syntax="make_date(year, month, day)",
        example="make_date(2024, 1, 15)",
        category=FunctionCategory.DATE,
        description_key="make_date",
        return_type="DATE",
        parameters=[
            FunctionParameter("year", "INTEGER", "param_year"),
            FunctionParameter("month", "INTEGER", "param_month"),
            FunctionParameter("day", "INTEGER", "param_day"),
        ],
        min_args=3,
        max_args=3,
    ),
    "strftime": FunctionDoc(
        name="strftime",
        syntax="strftime(format, date)",
        example="strftime('%Y-%m', \"date\")",
        category=FunctionCategory.DATE,
        description_key="strftime",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("format", "VARCHAR", "param_format"),
            FunctionParameter("date", "DATE", "param_date"),
        ],
        min_args=2,
        max_args=2,
    ),
    "age": FunctionDoc(
        name="age",
        syntax="age(timestamp)",
        example='age("birth_date")',
        category=FunctionCategory.DATE,
        description_key="age",
        return_type="INTERVAL",
        parameters=[FunctionParameter("timestamp", "TIMESTAMP", "param_timestamp")],
        min_args=1,
        max_args=2,
    ),
    # -------------------------------------------------------------------------
    # AGGREGATE FUNCTIONS
    # -------------------------------------------------------------------------
    "sum": FunctionDoc(
        name="sum",
        syntax="sum(x)",
        example='SUM("population") OVER ()',
        category=FunctionCategory.AGGREGATE,
        description_key="sum",
        return_type="NUMERIC",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "avg": FunctionDoc(
        name="avg",
        syntax="avg(x)",
        example='AVG("income")',
        category=FunctionCategory.AGGREGATE,
        description_key="avg",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "min": FunctionDoc(
        name="min",
        syntax="min(x)",
        example='MIN("value")',
        category=FunctionCategory.AGGREGATE,
        description_key="min",
        return_type="ANY",
        parameters=[FunctionParameter("x", "ANY", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "max": FunctionDoc(
        name="max",
        syntax="max(x)",
        example='MAX("value")',
        category=FunctionCategory.AGGREGATE,
        description_key="max",
        return_type="ANY",
        parameters=[FunctionParameter("x", "ANY", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "count": FunctionDoc(
        name="count",
        syntax="count(x)",
        example='COUNT("id")',
        category=FunctionCategory.AGGREGATE,
        description_key="count",
        return_type="BIGINT",
        parameters=[FunctionParameter("x", "ANY", "param_x")],
        min_args=0,
        max_args=1,
    ),
    "stddev": FunctionDoc(
        name="stddev",
        syntax="stddev(x)",
        example='STDDEV("value")',
        category=FunctionCategory.AGGREGATE,
        description_key="stddev",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "stddev_pop": FunctionDoc(
        name="stddev_pop",
        syntax="stddev_pop(x)",
        example='STDDEV_POP("value")',
        category=FunctionCategory.AGGREGATE,
        description_key="stddev_pop",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "stddev_samp": FunctionDoc(
        name="stddev_samp",
        syntax="stddev_samp(x)",
        example='STDDEV_SAMP("value")',
        category=FunctionCategory.AGGREGATE,
        description_key="stddev_samp",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "variance": FunctionDoc(
        name="variance",
        syntax="variance(x)",
        example='VARIANCE("value")',
        category=FunctionCategory.AGGREGATE,
        description_key="variance",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "var_pop": FunctionDoc(
        name="var_pop",
        syntax="var_pop(x)",
        example='VAR_POP("value")',
        category=FunctionCategory.AGGREGATE,
        description_key="var_pop",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "var_samp": FunctionDoc(
        name="var_samp",
        syntax="var_samp(x)",
        example='VAR_SAMP("value")',
        category=FunctionCategory.AGGREGATE,
        description_key="var_samp",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "median": FunctionDoc(
        name="median",
        syntax="median(x)",
        example='median("income")',
        category=FunctionCategory.AGGREGATE,
        description_key="median",
        return_type="DOUBLE",
        parameters=[FunctionParameter("x", "NUMERIC", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "quantile_cont": FunctionDoc(
        name="quantile_cont",
        syntax="quantile_cont(x, quantile)",
        example='quantile_cont("value", 0.75)',
        category=FunctionCategory.AGGREGATE,
        description_key="quantile_cont",
        return_type="DOUBLE",
        parameters=[
            FunctionParameter("x", "NUMERIC", "param_x"),
            FunctionParameter("quantile", "DOUBLE", "param_quantile"),
        ],
        min_args=2,
        max_args=2,
    ),
    "quantile_disc": FunctionDoc(
        name="quantile_disc",
        syntax="quantile_disc(x, quantile)",
        example='quantile_disc("value", 0.5)',
        category=FunctionCategory.AGGREGATE,
        description_key="quantile_disc",
        return_type="ANY",
        parameters=[
            FunctionParameter("x", "NUMERIC", "param_x"),
            FunctionParameter("quantile", "DOUBLE", "param_quantile"),
        ],
        min_args=2,
        max_args=2,
    ),
    "string_agg": FunctionDoc(
        name="string_agg",
        syntax="string_agg(x, separator)",
        example="string_agg(\"name\", ', ')",
        category=FunctionCategory.AGGREGATE,
        description_key="string_agg",
        return_type="VARCHAR",
        parameters=[
            FunctionParameter("x", "VARCHAR", "param_x"),
            FunctionParameter("separator", "VARCHAR", "param_separator"),
        ],
        min_args=2,
        max_args=2,
    ),
    "first": FunctionDoc(
        name="first",
        syntax="first(x)",
        example='first("name")',
        category=FunctionCategory.AGGREGATE,
        description_key="first",
        return_type="ANY",
        parameters=[FunctionParameter("x", "ANY", "param_x")],
        min_args=1,
        max_args=1,
    ),
    "last": FunctionDoc(
        name="last",
        syntax="last(x)",
        example='last("name")',
        category=FunctionCategory.AGGREGATE,
        description_key="last",
        return_type="ANY",
        parameters=[FunctionParameter("x", "ANY", "param_x")],
        min_args=1,
        max_args=1,
    ),
    # -------------------------------------------------------------------------
    # WINDOW FUNCTIONS
    # -------------------------------------------------------------------------
    "ntile": FunctionDoc(
        name="ntile",
        syntax="ntile(n)",
        example='ntile(5) OVER (ORDER BY "value")',
        category=FunctionCategory.WINDOW,
        description_key="ntile",
        return_type="BIGINT",
        parameters=[FunctionParameter("n", "INTEGER", "param_n")],
        min_args=1,
        max_args=1,
        requires_over=True,
    ),
    "percent_rank": FunctionDoc(
        name="percent_rank",
        syntax="percent_rank()",
        example='percent_rank() OVER (ORDER BY "value")',
        category=FunctionCategory.WINDOW,
        description_key="percent_rank",
        return_type="DOUBLE",
        parameters=[],
        min_args=0,
        max_args=0,
        requires_over=True,
    ),
    "cume_dist": FunctionDoc(
        name="cume_dist",
        syntax="cume_dist()",
        example='cume_dist() OVER (ORDER BY "value")',
        category=FunctionCategory.WINDOW,
        description_key="cume_dist",
        return_type="DOUBLE",
        parameters=[],
        min_args=0,
        max_args=0,
        requires_over=True,
    ),
    "row_number": FunctionDoc(
        name="row_number",
        syntax="row_number()",
        example='row_number() OVER (ORDER BY "date")',
        category=FunctionCategory.WINDOW,
        description_key="row_number",
        return_type="BIGINT",
        parameters=[],
        min_args=0,
        max_args=0,
        requires_over=True,
    ),
    "rank": FunctionDoc(
        name="rank",
        syntax="rank()",
        example='rank() OVER (ORDER BY "score" DESC)',
        category=FunctionCategory.WINDOW,
        description_key="rank",
        return_type="BIGINT",
        parameters=[],
        min_args=0,
        max_args=0,
        requires_over=True,
    ),
    "dense_rank": FunctionDoc(
        name="dense_rank",
        syntax="dense_rank()",
        example='dense_rank() OVER (ORDER BY "score")',
        category=FunctionCategory.WINDOW,
        description_key="dense_rank",
        return_type="BIGINT",
        parameters=[],
        min_args=0,
        max_args=0,
        requires_over=True,
    ),
    "lag": FunctionDoc(
        name="lag",
        syntax="lag(x, offset, default)",
        example='lag("value", 1) OVER (ORDER BY "date")',
        category=FunctionCategory.WINDOW,
        description_key="lag",
        return_type="ANY",
        parameters=[
            FunctionParameter("x", "ANY", "param_x"),
            FunctionParameter(
                "offset", "INTEGER", "param_offset", optional=True, default="1"
            ),
            FunctionParameter("default", "ANY", "param_default", optional=True),
        ],
        min_args=1,
        max_args=3,
        requires_over=True,
    ),
    "lead": FunctionDoc(
        name="lead",
        syntax="lead(x, offset, default)",
        example='lead("value", 1) OVER (ORDER BY "date")',
        category=FunctionCategory.WINDOW,
        description_key="lead",
        return_type="ANY",
        parameters=[
            FunctionParameter("x", "ANY", "param_x"),
            FunctionParameter(
                "offset", "INTEGER", "param_offset", optional=True, default="1"
            ),
            FunctionParameter("default", "ANY", "param_default", optional=True),
        ],
        min_args=1,
        max_args=3,
        requires_over=True,
    ),
    "first_value": FunctionDoc(
        name="first_value",
        syntax="first_value(x)",
        example='first_value("val") OVER (ORDER BY "date")',
        category=FunctionCategory.WINDOW,
        description_key="first_value",
        return_type="ANY",
        parameters=[FunctionParameter("x", "ANY", "param_x")],
        min_args=1,
        max_args=1,
        requires_over=True,
    ),
    "last_value": FunctionDoc(
        name="last_value",
        syntax="last_value(x)",
        example='last_value("val") OVER (ORDER BY "date")',
        category=FunctionCategory.WINDOW,
        description_key="last_value",
        return_type="ANY",
        parameters=[FunctionParameter("x", "ANY", "param_x")],
        min_args=1,
        max_args=1,
        requires_over=True,
    ),
    "nth_value": FunctionDoc(
        name="nth_value",
        syntax="nth_value(x, n)",
        example='nth_value("val", 2) OVER (ORDER BY "date")',
        category=FunctionCategory.WINDOW,
        description_key="nth_value",
        return_type="ANY",
        parameters=[
            FunctionParameter("x", "ANY", "param_x"),
            FunctionParameter("n", "INTEGER", "param_n"),
        ],
        min_args=2,
        max_args=2,
        requires_over=True,
    ),
    # -------------------------------------------------------------------------
    # SPATIAL FUNCTIONS
    # -------------------------------------------------------------------------
    "st_area": FunctionDoc(
        name="st_area",
        syntax="ST_Area(geometry)",
        example='ST_Area("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_area",
        return_type="DOUBLE",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_length": FunctionDoc(
        name="st_length",
        syntax="ST_Length(geometry)",
        example='ST_Length("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_length",
        return_type="DOUBLE",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_perimeter": FunctionDoc(
        name="st_perimeter",
        syntax="ST_Perimeter(geometry)",
        example='ST_Perimeter("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_perimeter",
        return_type="DOUBLE",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_x": FunctionDoc(
        name="st_x",
        syntax="ST_X(point)",
        example='ST_X("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_x",
        return_type="DOUBLE",
        parameters=[FunctionParameter("point", "GEOMETRY", "param_point")],
        min_args=1,
        max_args=1,
    ),
    "st_y": FunctionDoc(
        name="st_y",
        syntax="ST_Y(point)",
        example='ST_Y("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_y",
        return_type="DOUBLE",
        parameters=[FunctionParameter("point", "GEOMETRY", "param_point")],
        min_args=1,
        max_args=1,
    ),
    "st_centroid": FunctionDoc(
        name="st_centroid",
        syntax="ST_Centroid(geometry)",
        example='ST_Centroid("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_centroid",
        return_type="GEOMETRY",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_pointonsurface": FunctionDoc(
        name="st_pointonsurface",
        syntax="ST_PointOnSurface(geometry)",
        example='ST_PointOnSurface("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_pointonsurface",
        return_type="GEOMETRY",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_buffer": FunctionDoc(
        name="st_buffer",
        syntax="ST_Buffer(geometry, distance)",
        example='ST_Buffer("geometry", 100)',
        category=FunctionCategory.SPATIAL,
        description_key="st_buffer",
        return_type="GEOMETRY",
        parameters=[
            FunctionParameter("geometry", "GEOMETRY", "param_geometry"),
            FunctionParameter("distance", "DOUBLE", "param_distance"),
        ],
        min_args=2,
        max_args=2,
    ),
    "st_envelope": FunctionDoc(
        name="st_envelope",
        syntax="ST_Envelope(geometry)",
        example='ST_Envelope("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_envelope",
        return_type="GEOMETRY",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_simplify": FunctionDoc(
        name="st_simplify",
        syntax="ST_Simplify(geometry, tolerance)",
        example='ST_Simplify("geometry", 10)',
        category=FunctionCategory.SPATIAL,
        description_key="st_simplify",
        return_type="GEOMETRY",
        parameters=[
            FunctionParameter("geometry", "GEOMETRY", "param_geometry"),
            FunctionParameter("tolerance", "DOUBLE", "param_tolerance"),
        ],
        min_args=2,
        max_args=2,
    ),
    "st_convexhull": FunctionDoc(
        name="st_convexhull",
        syntax="ST_ConvexHull(geometry)",
        example='ST_ConvexHull("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_convexhull",
        return_type="GEOMETRY",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_transform": FunctionDoc(
        name="st_transform",
        syntax="ST_Transform(geometry, source_crs, target_crs)",
        example="ST_Transform(\"geometry\", 'EPSG:4326', 'EPSG:3857')",
        category=FunctionCategory.SPATIAL,
        description_key="st_transform",
        return_type="GEOMETRY",
        parameters=[
            FunctionParameter("geometry", "GEOMETRY", "param_geometry"),
            FunctionParameter("source_crs", "VARCHAR", "param_source_crs"),
            FunctionParameter("target_crs", "VARCHAR", "param_target_crs"),
        ],
        min_args=3,
        max_args=3,
    ),
    "st_numpoints": FunctionDoc(
        name="st_numpoints",
        syntax="ST_NumPoints(geometry)",
        example='ST_NumPoints("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_numpoints",
        return_type="INTEGER",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_geometrytype": FunctionDoc(
        name="st_geometrytype",
        syntax="ST_GeometryType(geometry)",
        example='ST_GeometryType("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_geometrytype",
        return_type="VARCHAR",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_isvalid": FunctionDoc(
        name="st_isvalid",
        syntax="ST_IsValid(geometry)",
        example='ST_IsValid("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_isvalid",
        return_type="BOOLEAN",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_isempty": FunctionDoc(
        name="st_isempty",
        syntax="ST_IsEmpty(geometry)",
        example='ST_IsEmpty("geometry")',
        category=FunctionCategory.SPATIAL,
        description_key="st_isempty",
        return_type="BOOLEAN",
        parameters=[FunctionParameter("geometry", "GEOMETRY", "param_geometry")],
        min_args=1,
        max_args=1,
    ),
    "st_distance": FunctionDoc(
        name="st_distance",
        syntax="ST_Distance(geometry_a, geometry_b)",
        example='ST_Distance("geom_a", "geom_b")',
        category=FunctionCategory.SPATIAL,
        description_key="st_distance",
        return_type="DOUBLE",
        parameters=[
            FunctionParameter("geometry_a", "GEOMETRY", "param_geometry_a"),
            FunctionParameter("geometry_b", "GEOMETRY", "param_geometry_b"),
        ],
        min_args=2,
        max_args=2,
    ),
    "st_intersects": FunctionDoc(
        name="st_intersects",
        syntax="ST_Intersects(geometry_a, geometry_b)",
        example='ST_Intersects("geometry", "boundary")',
        category=FunctionCategory.SPATIAL,
        description_key="st_intersects",
        return_type="BOOLEAN",
        parameters=[
            FunctionParameter("geometry_a", "GEOMETRY", "param_geometry_a"),
            FunctionParameter("geometry_b", "GEOMETRY", "param_geometry_b"),
        ],
        min_args=2,
        max_args=2,
    ),
    "st_contains": FunctionDoc(
        name="st_contains",
        syntax="ST_Contains(geometry_a, geometry_b)",
        example='ST_Contains("polygon", "point")',
        category=FunctionCategory.SPATIAL,
        description_key="st_contains",
        return_type="BOOLEAN",
        parameters=[
            FunctionParameter("geometry_a", "GEOMETRY", "param_geometry_a"),
            FunctionParameter("geometry_b", "GEOMETRY", "param_geometry_b"),
        ],
        min_args=2,
        max_args=2,
    ),
    "st_within": FunctionDoc(
        name="st_within",
        syntax="ST_Within(geometry_a, geometry_b)",
        example='ST_Within("point", "polygon")',
        category=FunctionCategory.SPATIAL,
        description_key="st_within",
        return_type="BOOLEAN",
        parameters=[
            FunctionParameter("geometry_a", "GEOMETRY", "param_geometry_a"),
            FunctionParameter("geometry_b", "GEOMETRY", "param_geometry_b"),
        ],
        min_args=2,
        max_args=2,
    ),
    # -------------------------------------------------------------------------
    # CONDITIONAL FUNCTIONS
    # -------------------------------------------------------------------------
    "coalesce": FunctionDoc(
        name="coalesce",
        syntax="coalesce(a, b, ...)",
        example="coalesce(\"name\", 'Unknown')",
        category=FunctionCategory.CONDITIONAL,
        description_key="coalesce",
        return_type="ANY",
        parameters=[FunctionParameter("values", "ANY", "param_values")],
        min_args=1,
        max_args=None,
    ),
    "nullif": FunctionDoc(
        name="nullif",
        syntax="nullif(a, b)",
        example='nullif("value", 0)',
        category=FunctionCategory.CONDITIONAL,
        description_key="nullif",
        return_type="ANY",
        parameters=[
            FunctionParameter("a", "ANY", "param_a"),
            FunctionParameter("b", "ANY", "param_b"),
        ],
        min_args=2,
        max_args=2,
    ),
    "ifnull": FunctionDoc(
        name="ifnull",
        syntax="ifnull(value, default)",
        example="ifnull(\"field\", 'default')",
        category=FunctionCategory.CONDITIONAL,
        description_key="ifnull",
        return_type="ANY",
        parameters=[
            FunctionParameter("value", "ANY", "param_value"),
            FunctionParameter("default", "ANY", "param_default"),
        ],
        min_args=2,
        max_args=2,
    ),
    "if": FunctionDoc(
        name="if",
        syntax="if(condition, then, else)",
        example="if(\"value\" > 0, 'Positive', 'Non-positive')",
        category=FunctionCategory.CONDITIONAL,
        description_key="if",
        return_type="ANY",
        parameters=[
            FunctionParameter("condition", "BOOLEAN", "param_condition"),
            FunctionParameter("then", "ANY", "param_then"),
            FunctionParameter("else", "ANY", "param_else"),
        ],
        min_args=3,
        max_args=3,
    ),
}


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def get_allowed_functions() -> set[str]:
    """Get the set of all allowed function names (lowercase)."""
    return set(FUNCTION_REGISTRY.keys())


def get_functions_by_category() -> dict[FunctionCategory, list[FunctionDoc]]:
    """Get functions grouped by category."""
    result: dict[FunctionCategory, list[FunctionDoc]] = {
        cat: [] for cat in FunctionCategory
    }
    for func in FUNCTION_REGISTRY.values():
        result[func.category].append(func)
    # Sort each category alphabetically
    for cat in result:
        result[cat].sort(key=lambda f: f.name)
    return result


def get_function_names_set() -> set[str]:
    """Get lowercase function names for validation."""
    return {name.lower() for name in FUNCTION_REGISTRY.keys()}


# Also allow common SQL keywords as functions
ALLOWED_KEYWORDS = {
    "case",
    "when",
    "then",
    "else",
    "end",
    "and",
    "or",
    "not",
    "in",
    "between",
    "like",
    "ilike",
    "is",
    "null",
    "true",
    "false",
    "cast",
    "as",
    "over",
    "partition",
    "by",
    "order",
    "asc",
    "desc",
    "nulls",
    "first",
    "last",
    "rows",
    "range",
    "unbounded",
    "preceding",
    "following",
    "current",
    "row",
    "distinct",
    "all",
    "filter",
    "where",
    "interval",
}

# Allowed type names for CAST
ALLOWED_TYPES = {
    "integer",
    "int",
    "bigint",
    "smallint",
    "tinyint",
    "double",
    "float",
    "real",
    "decimal",
    "numeric",
    "varchar",
    "text",
    "char",
    "boolean",
    "bool",
    "date",
    "timestamp",
    "time",
    "interval",
}
