"""add bundle tables

Revision ID: 12d658d174ae
Revises: init
Create Date: 2026-07-15 11:23:17.460624

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12d658d174ae'
down_revision = 'init'
branch_labels = None
depends_on = None

# The squashed `init` baseline builds the whole schema from the live SQLModel
# metadata via create_all, so on a FRESH database these tables already exist by
# the time this migration runs. init creates all model tables atomically in one
# transaction, so the presence of one is an all-or-nothing proxy for all five:
# skip on fresh DBs, create on existing (pre-bundle) DBs.
SCHEMA = "customer"
_PROBE_TABLE = "bundle_type"


def upgrade():
    bind = op.get_bind()
    if sa.inspect(bind).has_table(_PROBE_TABLE, schema=SCHEMA):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_type',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('to_char(CURRENT_TIMESTAMP AT TIME ZONE \'UTC\', \'YYYY-MM-DD"T"HH24:MI:SSOF\')::timestamptz'), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('type'),
    schema='customer'
    )
    op.create_table('bundle',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('to_char(CURRENT_TIMESTAMP AT TIME ZONE \'UTC\', \'YYYY-MM-DD"T"HH24:MI:SSOF\')::timestamptz'), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bundle_type', sa.Text(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='ready', nullable=False),
    sa.ForeignKeyConstraint(['bundle_type'], ['customer.bundle_type.type'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['folder_id'], ['customer.folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['customer.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_bundle_bundle_type'), 'bundle', ['bundle_type'], unique=False, schema='customer')
    op.create_table('bundle_artifact',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('to_char(CURRENT_TIMESTAMP AT TIME ZONE \'UTC\', \'YYYY-MM-DD"T"HH24:MI:SSOF\')::timestamptz'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['customer.bundle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_id', 'kind', name='uq_bundle_artifact_kind'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_bundle_artifact_bundle_id'), 'bundle_artifact', ['bundle_id'], unique=False, schema='customer')
    op.create_table('bundle_dependency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_bundle_id', sa.UUID(), nullable=False),
    sa.Column('dependency_kind', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['customer.bundle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_bundle_id'], ['customer.bundle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_id', 'dependency_kind', name='uq_bundle_dependency_kind'),
    schema='customer'
    )
    op.create_index('idx_bundle_dependency_depends_on', 'bundle_dependency', ['depends_on_bundle_id'], unique=False, schema='customer')
    op.create_index('idx_bundle_dependency_bundle', 'bundle_dependency', ['bundle_id'], unique=False, schema='customer')
    op.create_table('bundle_layer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('layer_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['customer.bundle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['layer_id'], ['customer.layer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_id', 'role', name='uq_bundle_layer_role'),
    sa.UniqueConstraint('layer_id', name='uq_bundle_layer_layer'),
    schema='customer'
    )
    op.create_index('idx_bundle_layer_bundle', 'bundle_layer', ['bundle_id'], unique=False, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    if not sa.inspect(bind).has_table(_PROBE_TABLE, schema=SCHEMA):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bundle_layer_bundle', table_name='bundle_layer', schema='customer')
    op.drop_table('bundle_layer', schema='customer')
    op.drop_index('idx_bundle_dependency_bundle', table_name='bundle_dependency', schema='customer')
    op.drop_index('idx_bundle_dependency_depends_on', table_name='bundle_dependency', schema='customer')
    op.drop_table('bundle_dependency', schema='customer')
    op.drop_index(op.f('ix_customer_bundle_artifact_bundle_id'), table_name='bundle_artifact', schema='customer')
    op.drop_table('bundle_artifact', schema='customer')
    op.drop_index(op.f('ix_customer_bundle_bundle_type'), table_name='bundle', schema='customer')
    op.drop_table('bundle', schema='customer')
    op.drop_table('bundle_type', schema='customer')
    # ### end Alembic commands ###
