"""add project custom_basemaps

Revision ID: ccb2a3c570b2
Revises: e8bd0e42b8eb
Create Date: 2026-04-30 17:19:49.886707

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccb2a3c570b2'
down_revision = 'e8bd0e42b8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project',
        sa.Column(
            'custom_basemaps',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        schema='customer',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'custom_basemaps', schema='customer')
    # ### end Alembic commands ###
