"""add custom domains

Revision ID: e8bd0e42b8eb
Revises: 8a1b2c3d4e5f
Create Date: 2026-04-27 18:21:06.914847

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = 'e8bd0e42b8eb'
down_revision = '8a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_domain',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('to_char(CURRENT_TIMESTAMP AT TIME ZONE \'UTC\', \'YYYY-MM-DD"T"HH24:MI:SSOF\')::timestamptz'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('base_domain', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='single', nullable=False),
    sa.Column('dns_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('dns_status_message', sa.Text(), nullable=True),
    sa.Column('dns_last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cert_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('cert_status_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['accounts.organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_organization_domain_base_domain'), 'organization_domain', ['base_domain'], unique=True, schema='customer')
    op.create_index(op.f('ix_customer_organization_domain_organization_id'), 'organization_domain', ['organization_id'], unique=False, schema='customer')
    op.add_column('project_public', sa.Column('custom_domain_id', sa.UUID(), nullable=True), schema='customer')
    op.add_column('project_public', sa.Column('subdomain', sa.Text(), nullable=True), schema='customer')
    op.add_column('project_public', sa.Column('tracking_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='customer')
    op.create_index(op.f('ix_customer_project_public_custom_domain_id'), 'project_public', ['custom_domain_id'], unique=True, schema='customer')
    op.create_foreign_key('fk_project_public_custom_domain_id_organization_domain', 'project_public', 'organization_domain', ['custom_domain_id'], ['id'], source_schema='customer', referent_schema='customer', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_project_public_custom_domain_id_organization_domain', 'project_public', schema='customer', type_='foreignkey')
    op.drop_index(op.f('ix_customer_project_public_custom_domain_id'), table_name='project_public', schema='customer')
    op.drop_column('project_public', 'tracking_enabled', schema='customer')
    op.drop_column('project_public', 'subdomain', schema='customer')
    op.drop_column('project_public', 'custom_domain_id', schema='customer')
    op.drop_index(op.f('ix_customer_organization_domain_organization_id'), table_name='organization_domain', schema='customer')
    op.drop_index(op.f('ix_customer_organization_domain_base_domain'), table_name='organization_domain', schema='customer')
    op.drop_table('organization_domain', schema='customer')
    # ### end Alembic commands ###
